/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GenerationsRouteImport } from './routes/generations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerationsIndexRouteImport } from './routes/generations.index'
import { Route as GenerationsIdRouteImport } from './routes/generations.$id'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsRoute = GenerationsRouteImport.update({
  id: '/generations',
  path: '/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsIndexRoute = GenerationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GenerationsRoute,
} as any)
const GenerationsIdRoute = GenerationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GenerationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generations': typeof GenerationsRouteWithChildren
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/generations/$id': typeof GenerationsIdRoute
  '/generations/': typeof GenerationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/generations/$id': typeof GenerationsIdRoute
  '/generations': typeof GenerationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generations': typeof GenerationsRouteWithChildren
  '/login': typeof LoginRoute
  '/playground': typeof PlaygroundRoute
  '/generations/$id': typeof GenerationsIdRoute
  '/generations/': typeof GenerationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generations'
    | '/login'
    | '/playground'
    | '/generations/$id'
    | '/generations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/playground' | '/generations/$id' | '/generations'
  id:
    | '__root__'
    | '/'
    | '/generations'
    | '/login'
    | '/playground'
    | '/generations/$id'
    | '/generations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerationsRoute: typeof GenerationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlaygroundRoute: typeof PlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations': {
      id: '/generations'
      path: '/generations'
      fullPath: '/generations'
      preLoaderRoute: typeof GenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations/': {
      id: '/generations/'
      path: '/'
      fullPath: '/generations/'
      preLoaderRoute: typeof GenerationsIndexRouteImport
      parentRoute: typeof GenerationsRoute
    }
    '/generations/$id': {
      id: '/generations/$id'
      path: '/$id'
      fullPath: '/generations/$id'
      preLoaderRoute: typeof GenerationsIdRouteImport
      parentRoute: typeof GenerationsRoute
    }
  }
}

interface GenerationsRouteChildren {
  GenerationsIdRoute: typeof GenerationsIdRoute
  GenerationsIndexRoute: typeof GenerationsIndexRoute
}

const GenerationsRouteChildren: GenerationsRouteChildren = {
  GenerationsIdRoute: GenerationsIdRoute,
  GenerationsIndexRoute: GenerationsIndexRoute,
}

const GenerationsRouteWithChildren = GenerationsRoute._addFileChildren(
  GenerationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerationsRoute: GenerationsRouteWithChildren,
  LoginRoute: LoginRoute,
  PlaygroundRoute: PlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
